SHIVAM_ECommerce/Models/Features.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SHIVAM_ECommerce.Models
{
    public class Features : BaseClass
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public decimal Price { get; set; }
    }
}

SHIVAM_ECommerce/Controllers/FeaturesController.cs
using SHIVAM_ECommerce.Attributes;
using SHIVAM_ECommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using System.Threading.Tasks;
using System.Net;
using SHIVAM_ECommerce.Extensions;
using System.Data.Entity;
namespace SHIVAM_ECommerce.Controllers
{

    [CustomAuthorize]
    public class FeaturesController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /Features/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadData()
        {

            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var searchitem = Request["search[value]"];
            int _searchInt = -1;
            if (int.TryParse(searchitem, out _searchInt))
            {
                _searchInt = int.Parse(searchitem);
            }
            else
            {
                _searchInt = -1;
            }
            //Find Order Column
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            var v = (from a in db.Features select a);
            if (!string.IsNullOrEmpty(searchitem))
            {

                v = v.Where(b => b.Description.Contains(searchitem) || b.Notes.Contains(searchitem) || b.Title.Contains(searchitem) || b.Price == _searchInt);
            }
            //SORT
            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
            {
                v = v.OrderBy(sortColumn + " " + sortColumnDir);
            }

            recordsTotal = v.Count();
            var data = v.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data.Select(x => new { x.Id, x.Title, x.Price, x.Description }) }, JsonRequestBehavior.AllowGet);
        }

        // GET: /Featured/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Features features = await db.Features.FindAsync(id);
            if (features == null)
            {
                return HttpNotFound();
            }
            return View(features);
        }

        // GET: /Featured/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Featured/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Price,CreatedDate,UpdatedDate,Sort,Description,Notes")] Features features)
        {
            if (ModelState.IsValid)
            {
                features.CreatedDate = DateTime.Now;
                features.UpdatedDate = DateTime.Now;
                db.Features.Add(features);
                await db.SaveChangesAsync();
                this.AddNotification("Featured Added successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }

            return View(features);
        }

        // GET: /Featured/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Features features = await db.Features.FindAsync(id);
            if (features == null)
            {
                return HttpNotFound();
            }
            return View(features);
        }

        // POST: /Featured/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Price,CreatedDate,UpdatedDate,Sort,Description,Notes")] Features features)
        {
            if (ModelState.IsValid)
            {
                features.UpdatedDate = DateTime.Now;
                db.Entry(features).State = EntityState.Modified;
                await db.SaveChangesAsync();
                this.AddNotification("Featured Updated successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            return View(features);
        }



        // POST: /Featured/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {

                var _planFeatures = db.PlanFeatures.Where(x => x.FeatureID == id);
                if (!_planFeatures.Any())
                {

                    Features features = await db.Features.FindAsync(id);
                    db.Features.Remove(features);
                    await db.SaveChangesAsync();
                    return Json(new { Success = true, ex = "" });
                }
                else
                {
                    return Json(new { Success = false, ex = "This feature is currently in use for existing plan." });
                }
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, ex = ex.Message.ToString() });
            }
        }
    }
}

SHIVAM_ECommerce/Views/Features/Create.cshtml
@model SHIVAM_ECommerce.Models.Features

@{
    ViewBag.Title = "Create Feature";
}



<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/Features">Feature</a>
    </li>
    <li class="breadcrumb-item active">Feature Create</li>
</ol>

<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-plus"></i> Create New Feature</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
              
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Price)
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" value="Create" class="btn btn-primary">
                            <i class="fa fa-check"></i>
                            Create
                            </button>
                        <a href="/Features" class="btn btn-gray">
                            <i class="fa fa-times"></i>
                        Cancel</a>
                    </div>
                </div>
            </div>
        }
    </div>

</div>





@section Scripts {



    @Scripts.Render("~/bundles/jqueryval")
}

SHIVAM_ECommerce/Views/Features/Delete.cshtml
@model SHIVAM_ECommerce.Models.Features

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Features</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SHIVAM_ECommerce/Views/Features/Details.cshtml
@model SHIVAM_ECommerce.Models.Features

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Features</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SHIVAM_ECommerce/Views/Features/Edit.cshtml
@model SHIVAM_ECommerce.Models.Features

@{
    ViewBag.Title = "Edit Features";
}

<h2>Edit</h2>

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/Features">Features</a>
    </li>
    <li class="breadcrumb-item active">Feature Edit</li>
</ol>

<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-pencil"></i> Edit Feature</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "Features", FormMethod.Post,
                            new { }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreatedDate)


                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Title)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Price)
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>



         

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" value="Create" class="btn btn-primary">
                            <i class="fa fa-check"></i>
                            Update
                        </button>
                        <a href="/Features" class="btn btn-gray">
                            <i class="fa fa-times"></i>
                            Cancel
                        </a>
                    </div>
                </div>
            </div>

        }
    </div>

</div>





@section Scripts {



    @Scripts.Render("~/bundles/jqueryval")

}

SHIVAM_ECommerce/Views/Features/Index.cshtml
@model IEnumerable<SHIVAM_ECommerce.Models.Features>

@{
    ViewBag.Title = "Index";
}

<div class="container">



    <!-- display errors -->
    <!-- display warnings -->
    <!-- display success -->
    <!-- display success -->





    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Features</a>
        </li>
        <li class="breadcrumb-item active">Features List</li>
    </ol>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title"><i class="fa fa-list"></i> Features </h3>
            <div class="flex-fill text-right">
                <a href="/Features/Create" class="btn btn-success"> <i class="fa fa-plus"></i> Add Feature</a>
            </div>
        </div>
        <div class="card-body">
            <table id="myTable" class="table table-striped table-bordered dt-responsive">
                <thead>
                    <tr>
                        <th>Feature Title</th>
                        <th>Price</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>

        </div>
    </div>









</div>

@section scripts{



    <script>


        var _datatable = "";

        $(document).ready(function () {
            _datatable = $("#myTable").DataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "ajax": {
                    "url": "/Features/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },
                "columns": [

                        {

                            "data": "Title", "name": "Title", "autoWidth": true
                        },
                          {

                              "data": "Price", "name": "Price", "autoWidth": true
                          },
                           {

                               "data": "Description", "name": "Description", "autoWidth": true
                           },

                         {
                             "orderable": false,
                             "mRender": function (data, type, row) {
                                 var _b = '  <a onclick="DeleteFeature(' + row.Id + ')"  class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" ><i class="fa fa-trash"  align="center"></i></a>';
                                 var _a = '<a href="/Features/Details?id=' + row.Id + '"  class="btn btn-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Details" ><i class="fa fa-list"  align="center"></i></a>';
                                 return '<a href="/Features/Edit?id=' + row.Id + '" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><i class="fa fa-pencil"  align="center"></i></a>  ' + _a + _b;
                             }
                         },
                ]
            });
        });

        function DeleteFeature(ID) {

            bootbox.confirm("Are you sure you want to delete this Feature ?", function (result) {

                if (result) {

                    $.ajax({
                        url: "/Features/Delete",
                        data: JSON.stringify({ id: ID }),
                        type: 'POST',
                        contentType: 'application/json',
                        dataType: 'json',
                        success: function (result) {
                            if (result.Success === true) {
                                _datatable.clear().draw();
                            } else {
                                bootbox.alert("error occurred during operation." + result.ex);
                            }
                        },
                        error: function (req, status, error) {
                            bootbox.alert(error);
                        }
                    });
                }




            });

        }


    </script>
}