SHIVAM_ECommerce/Models/FeaturedSupplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SHIVAM_ECommerce.Models
{
    public class FeaturedSupplier : BaseClass
    {
        [Required]
        public int SupplierID { get; set; }
        public string OfferMessage { get; set; }
        public string ImagePath { get; set; }

        [ForeignKey("SupplierID")]

        public virtual Supplier Supplier { get; set; }
    }
}

SHIVAM_ECommerce/Controllers/FeaturedSupplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SHIVAM_ECommerce.Models;
using SHIVAM_ECommerce.Attributes;
using System.Linq.Dynamic;
using SHIVAM_ECommerce.Extensions;
using System.IO;
namespace SHIVAM_ECommerce.Controllers
{
    [CustomAuthorize]
    public class FeaturedSupplierController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /FeaturedSupplier/
        public ActionResult Index()
        {
            var featuredsuppliers = db.FeaturedSuppliers.Include(f => f.Supplier);
            return View(featuredsuppliers.ToList());
        }
        public ActionResult LoadData()
        {

            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var searchitem = Request["search[value]"];
            int _searchInt = -1;
            if (int.TryParse(searchitem, out _searchInt))
            {
                _searchInt = int.Parse(searchitem);
            }
            else
            {
                _searchInt = -1;
            }
            //Find Order Column
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;

            var v = (from a in db.FeaturedSuppliers select a);
            if (!string.IsNullOrEmpty(searchitem))
            {

                v = v.Where(b => b.ImagePath.Contains(searchitem) || b.OfferMessage.Contains(searchitem) || b.Description.Contains(searchitem));
            }
            //SORT
            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
            {
                v = v.OrderBy(sortColumn + " " + sortColumnDir);
            }

            recordsTotal = v.Count();
            var data = v.Skip(skip).Take(pageSize).ToList();
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data.Select(x => new { x.Id, x.OfferMessage, x.ImagePath, x.Description, Name = x.Supplier.FirstName + " " + x.Supplier.LastName }) }, JsonRequestBehavior.AllowGet);
        }
        // GET: /FeaturedSupplier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeaturedSupplier featuredsupplier = db.FeaturedSuppliers.Find(id);
            if (featuredsupplier == null)
            {
                return HttpNotFound();
            }
            return View(featuredsupplier);
        }

        // GET: /FeaturedSupplier/Create
        public ActionResult Create()
        {
            ViewBag.SupplierID = new SelectList(db.Suppliers, "Id", "CompanyName");
            return View();
        }

        // POST: /FeaturedSupplier/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SupplierID,OfferMessage,ImagePath,CreatedDate,UpdatedDate,Sort,Description,Notes")] FeaturedSupplier featuredsupplier, HttpPostedFileBase ImagePath)
        {
            if (ModelState.IsValid)
            {

                if (ImagePath != null)
                {
                    string pic = System.IO.Path.GetFileName(ImagePath.FileName);
                    string path = System.IO.Path.Combine(
                                           Server.MapPath("~/FeaturedImages"), pic);
                    // file is uploaded
                    ImagePath.SaveAs(path);

                    featuredsupplier.ImagePath = pic;


                }
                featuredsupplier.CreatedDate = DateTime.Now;
                featuredsupplier.UpdatedDate = DateTime.Now;
                db.FeaturedSuppliers.Add(featuredsupplier);
                db.SaveChanges();
                this.AddNotification("Featured supplier added successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }

            ViewBag.SupplierID = new SelectList(db.Suppliers, "Id", "CompanyName", featuredsupplier.SupplierID);
            return View(featuredsupplier);
        }

        // GET: /FeaturedSupplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeaturedSupplier featuredsupplier = db.FeaturedSuppliers.Find(id);
            if (featuredsupplier == null)
            {
                return HttpNotFound();
            }
            ViewBag.SupplierID = new SelectList(db.Suppliers, "Id", "CompanyName", featuredsupplier.SupplierID);
            return View(featuredsupplier);
        }

        // POST: /FeaturedSupplier/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SupplierID,OfferMessage,ImagePath,CreatedDate,UpdatedDate,Sort,Description,Notes")] FeaturedSupplier featuredsupplier, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                featuredsupplier.UpdatedDate = DateTime.Now;

                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(
                     Server.MapPath("~/FeaturedImages"), pic);
                    // file is uploaded
                    file.SaveAs(path);

                    featuredsupplier.ImagePath = pic;


                }
                db.Entry(featuredsupplier).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Featured supplier updated successfully.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            ViewBag.SupplierID = new SelectList(db.Suppliers, "Id", "CompanyName", featuredsupplier.SupplierID);
            return View(featuredsupplier);
        }



        // POST: /Featured/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                FeaturedSupplier featuredsupplier = db.FeaturedSuppliers.Find(id);
                db.FeaturedSuppliers.Remove(featuredsupplier);
                db.SaveChanges();
                return Json(new { Success = true, ex = "" });
            }
            catch (Exception ex)
            {

                return Json(new { Success = false, ex = ex.Message.ToString() });
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SHIVAM_ECommerce/Views/FeaturedSupplier/Create.cshtml
@model SHIVAM_ECommerce.Models.FeaturedSupplier

@{
    ViewBag.Title = "Create";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/FeaturedSupplier">Featured Supplier</a>
    </li>
    <li class="breadcrumb-item active">Featured Supplier Create</li>
</ol>

<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-plus"></i> Create New Featured Supplier</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "FeaturedSupplier", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(model => model.SupplierID, "SupplierID", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("SupplierID", String.Empty)
                        @Html.ValidationMessageFor(model => model.SupplierID)
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">  Offer Message </label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.OfferMessage, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.OfferMessage)
                    </div>
                </div>

                <div class="form-group">

                    <label class="control-label col-md-2">  Image Path </label>

                    <div class="col-md-4">
                        @*<input type="file" name="ImagePath" id="ImagePath" value=" " />*@
                        <div class="custom-file">
                            <input type="file" class="custom-file-input form-control" name="ImagePath" id="ImagePath" accept="image/*">
                            <label class="custom-file-label">Choose file</label>
                        </div>
                        <div class="gallery"></div>
                        @Html.ValidationMessageFor(model => model.ImagePath)
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Description, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Notes, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.Notes)
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary btn-space"><i class="fa fa-check"></i> Create</button>
                        <a class="btn btn-secondary btn-gray" href="/FeaturedSupplier"><i class="fa fa-times"></i> Cancel</a>
                    </div>

                </div>
            </div>
        }
    </div>

</div>

@section Scripts {


    <script>
        $("select").addClass("form-control col-md-5")
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

SHIVAM_ECommerce/Views/FeaturedSupplier/Delete.cshtml
@model SHIVAM_ECommerce.Models.FeaturedSupplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FeaturedSupplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Supplier.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfferMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfferMessage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SHIVAM_ECommerce/Views/FeaturedSupplier/Details.cshtml
@model SHIVAM_ECommerce.Models.FeaturedSupplier

@{
    ViewBag.Title = "Details";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/FeaturedSupplier"> Featured Supplier</a>
    </li>
    <li class="breadcrumb-item active">Featured Supplier Details</li>
</ol>

<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-list"></i>Featured Supplier Detail </h3>
    </div>
    <div class="card-body">

        <table class="table table-bordered">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Supplier.CompanyName)


                </td>
                <td>
                    @Html.DisplayFor(model => model.Supplier.CompanyName)


                </td>

                <td>
                    @Html.DisplayNameFor(model => model.OfferMessage)


                </td>

                <td>
                    @Html.DisplayFor(model => model.OfferMessage)


                </td>

            </tr>

            <tr>
                <td>
                    Featured Image

                </td>
                <td>


                    <img src="@Url.Content("~/FeaturedImages/"+Model.ImagePath)"  height="100" width="100"/>


                </td>

                <td>
                    Description
                </td>
                <td>
                    @Html.DisplayFor(model => model.Description)
                </td>




            </tr>


        </table>
    </div>
</div>

SHIVAM_ECommerce/Views/FeaturedSupplier/Edit.cshtml
@model SHIVAM_ECommerce.Models.FeaturedSupplier

@{
    ViewBag.Title = "Edit";
}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/FeaturedSupplier">Featured Supplier</a>
    </li>
    <li class="breadcrumb-item active">Featured Supplier Update</li>
</ol>

<div class="card">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-pencil"></i> Update  Featured Supplier</h3>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "FeaturedSupplier", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.ImagePath)
                @Html.HiddenFor(model => model.CreatedDate)

                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(model => model.SupplierID, "SupplierID", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("SupplierID", String.Empty)
                        @Html.ValidationMessageFor(model => model.SupplierID)
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">  Offer Message </label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.OfferMessage, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.OfferMessage)
                    </div>
                </div>

              


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Description, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Notes, new { @class = "form-control col-md-5" })
                        @Html.ValidationMessageFor(model => model.Notes)
                    </div>
                </div>
                <div class="col-md-4">

                    <h4>Update Image</h4>


                    @if (Model.ImagePath != null)
                    {
                        <img style="height:100px; width:100px;" id="SupplierImage" src="@Url.Content("~/FeaturedImages/" + Model.ImagePath)" alt="Alternate Text" />
                        <br /><br />
                        <button type="button" class="btn btn-danger removeImage" onclick="RemoveImage()"><i class="fa fa-times"></i> Remove Image</button>
                    }


                    @if (Model.ImagePath == null)
                    {
                        <img style="height:100px; width:100px;" src="@Url.Content("~/FeaturedImages/no-image.png")" alt="Alternate Text" />
                    }




                    <div class="form-group">

                        <div class="col-md-10">
                            <label for="file">Upload Image:</label>
                            @*<input type="file" name="file" id="file" style="width: 100%;" />*@
                            <div class="custom-file">
                                <input type="file" class="custom-file-input form-control" name="file" id="file" >
                                <label class="custom-file-label">Choose file</label>
                            </div>
                            <div class="gallery"></div>
                        </div>


                    </div>


                </div>





                <div class="form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary btn-space"> <i class="fa fa-check"></i> Update</button>
                        <a class="btn btn-secondary btn-gray" href="/FeaturedSupplier"><i class="fa fa-times"></i> Cancel</a>
                    </div>

                </div>
            </div>
        }
    </div>

</div>

@section Scripts {

<style>
    /*.removeImage {
        position: absolute;
        height: 30px;
        width: 30px;
        border-radius: 100%;
        padding: 0px !important;
        text-align: center;
        top: 33px;
        right: 236px;
    }*/
</style>

    <script>
        $("select").addClass("form-control col-md-5")
        function RemoveImage() {
            $("#SupplierImage").remove();
            $(".removeImage").hide();
            $("#ImagePath").val("");
        }
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

SHIVAM_ECommerce/Views/FeaturedSupplier/Index.cshtml
@{
}
<div class="container">



    <!-- display errors -->
    <!-- display warnings -->
    <!-- display success -->
    <!-- display success -->





    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Featured Suppliers</a>
        </li>
        <li class="breadcrumb-item active">Featured Suppliers List</li>
    </ol>

    <div class="card">
        <div class="card-header">

            <h3 class="card-title"><i class="fe fe-user"></i> Featured Supplier </h3>
            <div class="flex-fill text-right">
                <a href="/FeaturedSupplier/Create" class="btn btn-success"> <i class="fa fa-plus"></i> Add Featured Supplier</a>
            </div>
        </div>
        <div class="card-body">
            <table id="myTable" class="table table-striped table-bordered dt-responsive">
                <thead>
                    <tr>
                        <th>Featured Image</th>
                        <th>Message</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>

        </div>
    </div>









</div>

@section scripts{



    <script>


        var _datatable = "";
        var Imagepath = @Url.Content("~/FeaturedImages/")
        $(document).ready(function () {
            _datatable = $("#myTable").DataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                "ajax": {
                    "url": "/FeaturedSupplier/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },
                "columns": [
                      {
                          "data": "ImagePath", "name": "ImagePath", "autoWidth": true,
                          "mRender": function (data, type, row) {
                              debugger;

                              if ($.trim(row.ImagePath) != "") {
                                  var _img = '<img style="height:50px; width:50px; border-radius:100%;" src="' + Imagepath + row.ImagePath + ' "></img>';
                              }

                              else {
                                  var _img = '<img style="height:50px; width:50px; border-radius:100%;" src="' + Imagepath + "no-image.png" + '  "></img>';

                              }


                              return _img;
                          }
                      },
                        {

                            "data": "OfferMessage", "name": "OfferMessage", "autoWidth": true
                        },
                          {

                              "data": "Name", "name": "Name", "autoWidth": true, "orderable": false,
                          },
                           {

                               "data": "Description", "name": "Description", "autoWidth": true
                           },

                         {
                             "orderable": false,
                             "mRender": function (data, type, row) {
                                 var _a = '<a href="/FeaturedSupplier/Details?id=' + row.Id + '"  class="dropdown-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Details" ><i class="fa fa-list"  align="center"></i> Details</a>';
                                 var _c = '<a href="/FeaturedSupplier/Edit?id=' + row.Id + '" class="dropdown-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><i class="fa fa-pencil"  align="center"></i> Edit Featured Supplier</a>  '
                                 var _d = '<a onclick="DeleteFeaturedSupplier(' + row.Id + ')" href="#"  class="dropdown-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><i class="fa fa-trash"  align="center"></i> Delete Featured Supplier</a>  '


                                 return '<div class="item-action dropdown"><a href="javascript:void(0)" data-toggle="dropdown" class="icon" aria-expanded="false"><i class="fe fe-more-vertical"></i></a><div class="dropdown-menu dropdown-menu-right" x-placement="top-end" style="position: absolute; transform: translate3d(-177px, -139px, 0px); top: 0px; left: 0px; will-change: transform;">' + _c + _a + _d + '</div></div>';
                             }
                         },
                ]
            });
        });




        function DeleteFeaturedSupplier(Id) {

            bootbox.confirm("Are you sure you want to delete this featured supplier ?", function (result) {

                if (result) {

                    $.ajax({
                        url: "/FeaturedSupplier/Delete",
                        data: JSON.stringify({ ID: Id }),
                        type: 'POST',
                        contentType: 'application/json',
                        dataType: 'json',
                        success: function (result) {
                            if (result.Success === true) {
                                _datatable.clear().draw();
                            } else {
                                bootbox.alert("error occurred during operation." + result.ex);
                            }
                        },
                        error: function (req, status, error) {
                            bootbox.alert(error);
                        }
                    });
                }




            });

        }

    </script>
}